config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  post 'root' => 'welcome#search', as: :search_artist
  get 'artists' => 'artists#list', as: :artists
  get 'artists/:id' => 'artists#show', as: :artist
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

def list
  unless params[:artist_name].empty?
    @artists = RSpotify::Artist.search(params[:artist_name])
  else
    redirect_to root_path
  end
end


def show
  @artist = RSpotify::Artist.find(params[:id])
end

def album_show
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def home
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/list.html.erb
<div class="container">
  <h1>Search Results for: <%= params[:artist_name] %></h1>
  <hr>
   <% @artists.each do |artist| %>
     <%= link_to artist.name, artist_path(artist.id), class: "album-list" %> <br>
   <% end %>
</div>

app/views/artists/show.html.erb
<div class="container">

  <div class="page-header">
    <h1><%= @artist.name %></h1>
  </div>

  <% @artist.albums(country: 'US').each do |album| %>
  <div class="row">
    <div class="col-xs-4 col-sm-3">
        <%= image_tag(album.images.first["url"], :class => "album-image") %>
    </div>

    <div class="col-xs-6 col-sm-8">
      <h3><%= album.name %></h3> <br>
      Released on : <%= album.release_date %>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-xs-offset-1">
      <% album.tracks.each do |track| %>
      <%= track.track_number %> - <%= track.name %> - <%= Time.at(track.duration_ms/1000).utc.strftime("%M:%S")%> <br>
      <% end %>
    </div>

  </div>

  <hr>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtistWebApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-text">
          <strong><%= link_to "Artist-Finder Home", root_path, class: "navbar-home" %></strong>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/welcome/home.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center">Discover new Artists</h1>
  </div>

<div class="row">
  <div class="well well-lg col-xs-6 col-xs-offset-3">
    <%= form_tag artists_path, method: "get", html: { class: "form" } do %>
     <div class="col-xs-8">
       <%= text_field_tag(:artist_name, "", placeholder: "Enter artist name", class: "form-control") %>
     </div>
     <div class="col-xs-4">
       <%= submit_tag "Search", class: "form-control btn btn-block btn-primary" %>
     </div>
    <% end %>
  </div>
</div>




</div>